### ISSUE TITLE
Please provide import/export functionality

### ISSUE THREAD

**Issue by andreicristianpetcu** [ylecuyer/envify#10]
Hi!

This addon is AWESOME!!! :100:

Please provide some import/export or sync with FF sync.

Thank you, 
Andrei Petcu

**Comment by etiennewan** [comment]
Great idea! Firefox Sync sounds like a needed feature :+1:

**Comment by ylecuyer** [comment]
I have a fix ready for this. I will ping you when it is available @andreicristianpetcu

**Comment by andreicristianpetcu** [comment]
sweet :D

**Comment by ylecuyer** [comment]
@andreicristianpetcu the import/export functionality will be added in #22 

I'll release a new version of the extension with it this weekend
