### ISSUE TITLE
Does not work correctly with dark theme

### ISSUE THREAD

**Issue by garrettw** [ylecuyer/envify#11]
I am using Firefox Developer Edition with the built-in Dark theme, and on tabs that do not match a pattern, Envify sets the tab and toolbar color to white rather than the color actually defined in the theme. (The tab bar, however, stays dark.)

Furthermore, just disabling Envify does not fix the problem; I also have to restart Firefox for the Dark theme to fully take effect again.

**Comment by etiennewan** [comment]
This is related to #7 because we reset the theme, and the theme API behaviour is to reset to default not to the user's theme.
It should be fixed at the same time #7 is closed.

**Comment by tzikas97** [comment]
@garrettw You can check out my _solution_ [**here**](https://github.com/ylecuyer/envify/issues/7#issuecomment-392199728).

**Comment by garrettw** [comment]
Not the worst idea, at least as a stop-gap.
