### ISSUE TITLE
Loose config

### ISSUE THREAD

**Issue by ptigob** [ylecuyer/envify#24]
Bonjour,

Le plugin perds sa config régulièrement ce qui impose de la refaire, ou la ré-importer.

Aucune idée fiable de la raison... 
une hypothèse : La mise à jour automatique de celui-ci provoque la perte

Hi,

The plugin regularly loses its config, which requires redoing it, or re-importing it.

No reliable idea of the reason ...
an assumption: The automatic update of it causes the loss

**Comment by ylecuyer** [comment]
Hi @ptigob yes this is a known issue that I had no idea how to fix until a few days ago. @ajoah did a great investigation on #21 you can do the follow up here :)
