### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by bassamanator** [ylecuyer/envify#29]
How does this extension work? I've enabled it but nothings happening.

**Comment by ylecuyer** [comment]
On the first install the setting windows should have been displayed. If it is not the case, you can go to firefox > addons > extensions > Envify > ... >  Preferences to create your rules:

![Screenshot_2020-06-03_17-58-07](https://user-images.githubusercontent.com/1866809/83659453-da6cf180-a5c3-11ea-9288-a1d8d013c95b.png)

![Screenshot_2020-06-03_17-59-23](https://user-images.githubusercontent.com/1866809/83659541-f7a1c000-a5c3-11ea-8c58-d193d8fdac08.png)

**Comment by bassamanator** [comment]
Oh wow. What a great thing.

Thanks!
